/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sdbtester.gui;

import java.awt.CardLayout;
import java.awt.event.*;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import sdbtester.TestCaseSettings;

/**
 *
 * @author boris
 */
public class StartForm extends javax.swing.JFrame {

    private TestCaseSettings appSettings;
    private static Logger logger = Logger.getLogger(StartForm.class);

    /**
     * Creates new form StartForm
     */
    public StartForm() {
        initComponents();
        appSettings = TestCaseSettings.getInstance();
        btnBackTestCreation.setEnabled(false);
        btnForwardTestCreation.setEnabled(false);
        jPanelNameOfTest1.getJtextNameOfTestCase().addKeyListener(new KeyAdapter() {

            @Override
            public void keyTyped(KeyEvent ke) {
                if (jPanelNameOfTest1.getJtextNameOfTestCase().getText().length() > 1) {
                    btnForwardTestCreation.setEnabled(true);
                } else {
                    btnForwardTestCreation.setEnabled(false);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPainMain = new javax.swing.JTabbedPane();
        PanelTesting = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnBackTestCreation = new javax.swing.JButton();
        btnForwardTestCreation = new javax.swing.JButton();
        PanelTestingCards = new javax.swing.JPanel();
        jPanelNameOfTest1 = new sdbtester.gui.CardNameOfTest();
        dbConnectSettings1 = new sdbtester.gui.CardMysqlDbSettings();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBackTestCreation.setText("Назад");
        jPanel6.add(btnBackTestCreation);

        btnForwardTestCreation.setText("Вперед");
        btnForwardTestCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardTestCreationActionPerformed(evt);
            }
        });
        jPanel6.add(btnForwardTestCreation);

        PanelTestingCards.setLayout(new java.awt.CardLayout());
        PanelTestingCards.add(jPanelNameOfTest1, "CreateTestCaseCard");

        javax.swing.GroupLayout dbConnectSettings1Layout = new javax.swing.GroupLayout(dbConnectSettings1);
        dbConnectSettings1.setLayout(dbConnectSettings1Layout);
        dbConnectSettings1Layout.setHorizontalGroup(
            dbConnectSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        dbConnectSettings1Layout.setVerticalGroup(
            dbConnectSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        PanelTestingCards.add(dbConnectSettings1, "card3");

        javax.swing.GroupLayout PanelTestingLayout = new javax.swing.GroupLayout(PanelTesting);
        PanelTesting.setLayout(PanelTestingLayout);
        PanelTestingLayout.setHorizontalGroup(
            PanelTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTestingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PanelTestingCards, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        PanelTestingLayout.setVerticalGroup(
            PanelTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTestingLayout.createSequentialGroup()
                .addComponent(PanelTestingCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPainMain.addTab("Тестирование", PanelTesting);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPainMain.addTab("Анализ", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jTabbedPainMain.addTab("Настройки", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1014, 1014, 1014))
                    .addComponent(jTabbedPainMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPainMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForwardTestCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardTestCreationActionPerformed
        if (appSettings.setCurrentTestName(jPanelNameOfTest1.getJtextNameOfTestCase().getText(), jPanelNameOfTest1.getComboBoxDbTypes().getSelectedItem().toString())) {
//            CardLayout card = 
        }
    }//GEN-LAST:event_btnForwardTestCreationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StartForm().setVisible(true);
            }
        });


    }

    JPanel makePane() {
        JPanel p = new JPanel();
        p.setOpaque(false);
        return p;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTesting;
    private javax.swing.JPanel PanelTestingCards;
    private javax.swing.JButton btnBackTestCreation;
    private javax.swing.JButton btnForwardTestCreation;
    private sdbtester.gui.CardMysqlDbSettings dbConnectSettings1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private sdbtester.gui.CardNameOfTest jPanelNameOfTest1;
    private javax.swing.JTabbedPane jTabbedPainMain;
    // End of variables declaration//GEN-END:variables
}
